name: collection artifact

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - dedede
          - hana
          - hatch
          - nissa
          - octopus

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Legacy Sh1mmer
        env:
          board: ${{ matrix.board }}
        run: |
          set -e
          chmod +x ./wax/wax.sh
          sudo apt update
          sudo apt install -y pv unzip wget

          echo "Downloading file from https://dl.cros.download/files/${board}/${board}.zip..."
          wget -q "https://dl.cros.download/files/${board}/${board}.zip" -O "./${board}.zip"

          unzip "./${board}.zip"
          shim=$(unzip -Z1 "./${board}.zip")
          rm "./${board}.zip"

          echo "Using shim: $shim"
          sudo ./wax/wax.sh -i "$shim" -p "$board"

      - name: Upload built shim as artifact
        uses: actions/upload-artifact@v4
        with:
          name: legacy-sh1mmer-${{ matrix.board }}
          path: ./${{ matrix.board }}.bin
